blank_issues_enabled: false
contact_links:
  - name: Questions and Support
    url: https://github.com/bradmca/linkedin-respose-generator-lm-studio/discussions
    about: Please ask and answer questions here
  - name: Security Issues
    url: mailto:[INSERT SECURITY EMAIL]
    about: Please report security vulnerabilities privately
